### ISSUE TITLE
Crash hmm. 

### ISSUE THREAD

**Issue by aRandomMenno** [Hamza417/Inure#104]
My device is a motorola edge 20 lite. 

```
java.lang.RuntimeException: Unable to stop service app.simple.inure.terminal.TermService@1a8fc9: java.lang.NullPointerException: Attempt to invoke virtual method 'void app.simple.inure.decorations.emulatorview.TerminalEmulator.finish()' on a null object reference
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4830)
	at android.app.ActivityThread.access$2200(ActivityThread.java:261)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2197)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void app.simple.inure.decorations.emulatorview.TerminalEmulator.finish()' on a null object reference
	at app.simple.inure.decorations.emulatorview.TermSession.finish(TermSession.java:610)
	at app.simple.inure.terminal.GenericTermSession.finish(GenericTermSession.java:125)
	at app.simple.inure.terminal.ShellTermSession.finish(ShellTermSession.java:215)
	at app.simple.inure.terminal.TermService.onDestroy(TermService.java:121)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4810)
	... 9 more
```

**Comment by Hamza417** [comment]
Could you tell me how to reproduce this error?

**Comment by aRandomMenno** [comment]
I have no idea sorry, I way just exploring in the app and it just crashed with this error.

**Comment by Hamza417** [comment]
The cause of the error is unknown, so, I have handled it and this probably won't crash.
