### ISSUE TITLE
The app was crashed!

### ISSUE THREAD

**Issue by ventura-lepgs** [Hamza417/Inure#106]
java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
	at app.simple.inure.decorations.views.BottomMenuRecyclerView.lambda$initBottomMenu$0$app-simple-inure-decorations-views-BottomMenuRecyclerView(BottomMenuRecyclerView.java:76)
	at app.simple.inure.decorations.views.BottomMenuRecyclerView$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by Hamza417** [comment]
@ventura-lepgs In which panel did this happen?
