### ISSUE TITLE
A million times over on every device I own.
Recreate the issue by launching the app 
Android 10/11/13 magisk rooted.
Build 76

The app was crashed!

### ISSUE THREAD

**Issue by Itsfitts** [Hamza417/Inure#159]
java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ApplicationPackageManager.getInstalledPackagesAsUser(ApplicationPackageManager.java:1031)
	at android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:1016)
	at app.simple.inure.extensions.viewmodels.PackageUtilsViewModel.loadInstalledApps(PackageUtilsViewModel.kt:85)
	at app.simple.inure.extensions.viewmodels.PackageUtilsViewModel.getInstalledApps(PackageUtilsViewModel.kt:35)
	at app.simple.inure.viewmodels.panels.UsageStatsViewModel.getUsageStats(UsageStatsViewModel.kt:94)
	at app.simple.inure.viewmodels.panels.UsageStatsViewModel.access$getUsageStats(UsageStatsViewModel.kt:22)
	at app.simple.inure.viewmodels.panels.UsageStatsViewModel$loadAppStats$1.invokeSuspend(UsageStatsViewModel.kt:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dbb1ae7, Dispatchers.Default]
Caused by: android.os.DeadSystemException
	... 13 more

**Comment by Hamza417** [comment]
Check in Build77 if this issue occurs again.

**Comment by Hamza417** [comment]
Haven't encountered any error lately after the new loader framework has been added. I'm closing this issue now, you can reopen this if you encounter any again.
