### ISSUE TITLE
App can't be launched

### ISSUE THREAD

**Issue by Juloboy** [Hamza417/Inure#185]
![Screenshot_20230627-152619_Inure](https://github.com/Hamza417/Inure/assets/59500988/a23c0831-3e9a-46fd-9106-15dd84cb16cb)
The app can't be launched. Endless loading screen. The entire system is not properly responding while this process until I kill Inure app.
 - Device: [Poco X3 NFC]
 - OS: [Crdroid ROM Android 13]
 - Version [Build80]

**Comment by Hamza417** [comment]
@Juloboy I'm working on it.

**Comment by Juloboy** [comment]
> @Juloboy I'm working on it.

Is this issue available only on A13 ROMs?

**Comment by Hamza417** [comment]
@Juloboy I'm not entirely sure. I tested the app on all my devices and it's loading fine and all of them are running on Android 13. I'll have to dig deeper to know the real cause of the issue.

**Comment by Juloboy** [comment]
Thanks, hope the issue will be fixed!🙏 I liked the beautiful UI of the app!

**Comment by Juloboy** [comment]
java.lang.IllegalArgumentException: Service not registered: app.simple.inure.ui.launcher.SplashScreen$onViewCreated$2@7bd2105
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1991)
	at android.app.ContextImpl.unbindService(ContextImpl.java:2076)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:889)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:889)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:889)
	at app.simple.inure.ui.launcher.SplashScreen.onDestroy(SplashScreen.kt:387)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3376)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:811)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.kt:664)
	at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.kt:587)
	at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.kt:774)
	at androidx.fragment.app.DefaultSpecialEffectsController$startAnimations$3.onAnimationEnd$lambda$0(DefaultSpecialEffectsController.kt:273)
	at androidx.fragment.app.DefaultSpecialEffectsController$startAnimations$3.$r8$lambda$e4JYQPCwrudQZpKmEdhGp1_4AOE(Unknown Source:0)
	at androidx.fragment.app.DefaultSpecialEffectsController$startAnimations$3$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7896)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)


Build 82

**Comment by Juloboy** [comment]
Finally successfully launched the build 83. Thanks! 🙏
