### ISSUE TITLE
Apps button

### ISSUE THREAD

**Issue by islam2hamy** [Hamza417/Inure#25]
java.lang.NoSuchFieldError: No field category of type I in class Landroid/content/pm/ApplicationInfo; or its superclasses (declaration of 'android.content.pm.ApplicationInfo' appears in /system/framework/framework.jar)
	at app.simple.inure.util.PackageListUtils.setAppInfo(PackageListUtils.kt:31)
	at app.simple.inure.adapters.ui.AdapterAppsDetailed.onBindViewHolder(AdapterAppsDetailed.kt:55)
	at app.simple.inure.adapters.ui.AdapterAppsDetailed.onBindViewHolder(AdapterAppsDetailed.kt:23)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2390)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2112)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1298)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
	at android.view.Choreographer.doFrame(Choreographer.java:623)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by Hamza417** [comment]
_This error has been fixed_
