### ISSUE TITLE
error

### ISSUE THREAD

**Issue by baran1318** [Hamza417/Inure#315]
android.content.pm.PackageManager$NameNotFoundException: com.android.ld.appstore
	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:181)
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:152)
	at app.simple.inure.viewmodels.panels.BootManagerViewModel.getPackageInfo(BootManagerViewModel.kt:307)
	at app.simple.inure.viewmodels.panels.BootManagerViewModel.access$getPackageInfo(BootManagerViewModel.kt:28)
	at app.simple.inure.viewmodels.panels.BootManagerViewModel$loadBootComponents$1.invokeSuspend(BootManagerViewModel.kt:86)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f89c1c8, Dispatchers.IO]

**Comment by Hamza417** [comment]
I've [fixed this issue](https://github.com/Hamza417/Inure/commit/49ca040f7d91739e23fee122777a3288f6ecdb4b), thanks for the reporting,
