### ISSUE TITLE
error on enabling shizuku 

### ISSUE THREAD

**Issue by RobotsAreCrazy** [Hamza417/Inure#319]
installed on galaxy tab s6 (A12)
app version Build100.2.7 -1 on enabling shizuku, i receive the following
error: 
```java

java.lang.IllegalStateException: binder haven't been received
	at rikka.shizuku.Shizuku.requireService(Shizuku.java:411)
	at rikka.shizuku.Shizuku.checkSelfPermission(Shizuku.java:818)
	at app.simple.inure.ui.preferences.mainscreens.ConfigurationScreen.checkPermission(ConfigurationScreen.kt:203)
	at app.simple.inure.ui.preferences.mainscreens.ConfigurationScreen.onViewCreated$lambda$11(ConfigurationScreen.kt:168)
	at app.simple.inure.ui.preferences.mainscreens.ConfigurationScreen.$r8$lambda$erwEk_qAmNdaS5p8iGKxjE2jaqg(Unknown Source:0)
	at app.simple.inure.ui.preferences.mainscreens.ConfigurationScreen$$ExternalSyntheticLambda1.onCheckedChanged(D8$$SyntheticClass:0)
	at app.simple.inure.decorations.toggles.Switch.lambda$init$0(Switch.java:154)
	at app.simple.inure.decorations.toggles.Switch.$r8$lambda$9Nd5wQC7NcC72yoD-T3ug3dKzqk(Unknown Source:0)
	at app.simple.inure.decorations.toggles.Switch$$ExternalSyntheticLambda3.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7814)
	at android.view.View.performClickInternal(View.java:7791)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30419)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8855)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by Hamza417** [comment]
This issue was appearing in some devices, and it was [fixed a few days ago in this commit](https://github.com/Hamza417/Inure/commit/212717188eda4933f7cdb69f1ad88d4f6389ac0a). I'll publish a release including the fix in a few days.
