### ISSUE TITLE
The app was crashed!

### ISSUE THREAD

**Issue by ventura-lepgs** [Hamza417/Inure#52]
```java
java.lang.UnsupportedOperationException: File type not supported
	at app.simple.inure.viewmodels.installer.InstallerViewModel.prepareInstallation(InstallerViewModel.kt:77)
	at app.simple.inure.viewmodels.installer.InstallerViewModel.access$prepareInstallation(InstallerViewModel.kt:27)
	at app.simple.inure.viewmodels.installer.InstallerViewModel$packageInfo$2$1$1.invokeSuspend(InstallerViewModel.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Hamza417** [comment]
Could you also attach the file you were trying to install?

**Comment by Hamza417** [comment]
_I have fixed many issues related to installer panel. Due to lack of any further information, I'm closing this issue now._
