### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object kotlin.Lazy.getValue()' on a null object reference

### ISSUE THREAD

**Issue by Hamza417** [Hamza417/Inure#64]
``` java
Process: app.simple.inure, PID: 18705
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object kotlin.Lazy.getValue()' on a null object reference
        at app.simple.inure.viewmodels.panels.HomeViewModel.getRecentlyInstalledAppData(HomeViewModel.kt:40)
        at app.simple.inure.viewmodels.panels.HomeViewModel.access$getRecentlyInstalledAppData(HomeViewModel.kt:28)
        at app.simple.inure.viewmodels.panels.HomeViewModel$loadRecentlyInstalledAppData$1.invokeSuspend(HomeViewModel.kt:104)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6845302, Dispatchers.Default]
```

**Comment by Hamza417** [comment]
_I hope I don't have to open this again!_
